[node name="Butterflies2" type="Node3D" parent="." unique_id=915817820]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 3.1347141, 0, -11.073883)

[node name="Butterfly0" parent="Butterflies2" unique_id=1446814093 instance=ExtResource("forest_butterfly")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, -1.9, 1, 5.3)
flight_radius = 1.25

[node name="Butterfly1" parent="Butterflies2" unique_id=1355220998 instance=ExtResource("forest_butterfly")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, -0.8, 1.25, 4.7)
phase = 1.63
flight_radius = 1.25

[node name="Butterfly2" parent="Butterflies2" unique_id=674898267 instance=ExtResource("forest_butterfly")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, -1, 0.85, 2.8)
phase = 3.26
flight_radius = 1.25

[node name="AcornGuard2" parent="." unique_id=203052794 instance=ExtResource("Acorn")]
transform = Transform3D(0.99715644, 0, 0.07535918, 0, 1, 0, -0.07535918, 0, 0.99715644, 4.9946175, 0, -4.177539)

[node name="ForestKeeper2" parent="." unique_id=1864699252 instance=ExtResource("Keeper")]
transform = Transform3D(-4.371139e-08, 0, -1, 0, 1, 0, 1, 0, -4.371139e-08, 3.606892, -0.0024261475, -19.075542)
